/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package SinhVien;
import java.sql.*;
import javax.swing.*;;
import Process.*;
import Data.*;
import Process.*;
import Data.*;import Process.*;
import Data.*;
import static Process.ChucNang.conn;
import static Process.ChucNang.pts;
import java.io.BufferedOutputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author son
 */
public class Sinhvien extends javax.swing.JFrame {
    Connection conn=Connect.KetNoi();
    public static String  sql="Select * from  Students  ";
      
    public void Show(){
          Uptable.LoadData(sql, tbsinhvien);
          txttong.setText("Tổng số sinh viên: "+tbsinhvien.getRowCount());
    }
    public Sinhvien() {
        initComponents();
        show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        txttentim = new javax.swing.JTextField();
        btnload = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtdiemtb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtns = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsinhvien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnsua = new javax.swing.JButton();
        txttong = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btnExport = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnload.setText("Load");
        btnload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloadActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel5.setText("Nhập tên");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("ĐiểmTB");

        tbsinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "BirthDate", "Gioi tịnh", "DiemTB", "Khoa"
            }
        ));
        tbsinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbsinhvienEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbsinhvien);

        jLabel2.setText("ID");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("THÔNG TIN SINH VIÊN");

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        jLabel4.setText("BirthDate");

        jLabel3.setText("Name");

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        txttong.setText("Tổng sinh viên");

        btnExport.setText("Xuất file");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        jLabel7.setText("Giới tính");

        buttonGroup1.add(radioNam);
        radioNam.setText("Nam");

        buttonGroup1.add(radioNu);
        radioNu.setText("Nữ");

        jLabel8.setText("Khoa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txttong)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtns, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                                            .addComponent(txtname))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radioNam)
                                        .addGap(36, 36, 36)
                                        .addComponent(radioNu)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtKhoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                                            .addComponent(txtdiemtb, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txttentim, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnthem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtns, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioNu)
                    .addComponent(radioNam)
                    .addComponent(jLabel7)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6))
                    .addComponent(btnload, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttentim, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txttong)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        Show();
    }//GEN-LAST:event_btnloadActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if(txtid.getText().length()==0){
            JOptionPane.showMessageDialog(null,"Bạn chưa nhập id");
        }else{
            int f=JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa không","Thông báo",JOptionPane.OK_CANCEL_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(f==JOptionPane.OK_OPTION){
                ChucNang.Delete(txtid.getText().trim());
                Show();
                txtid.setText("");
                txtname.setText("");
                txtns.setText("");
                txtdiemtb.setText("");
            }
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String sql="Select * from Students where Name like N'%"+txttentim.getText()+"%'";
            Uptable.LoadData(sql, tbsinhvien);
            if(tbsinhvien.getRowCount()==0){
                JOptionPane.showMessageDialog(null,"Không tìm thấy");
            }else{
                JOptionPane.showMessageDialog(null,"Tìm thấy");
            }
            txttong.setText("Tổng số sinh viên tìm thấy:  "+tbsinhvien.getRowCount());
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbsinhvienEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbsinhvienEmployeesMouseClicked
        // TODO add your handling code here:
        try{
            int row=this.tbsinhvien.getSelectedRow();
            String Idrow=(this.tbsinhvien.getModel().getValueAt(row, 0)).toString();
            String sql1="Select * from Students where ID='"+Idrow+"' ";
            ResultSet rs=Uptable.ShowText(sql1);
            if(rs.next()){
                this.txtid.setText(rs.getString("ID"));
                this.txtname.setText(rs.getString("Name"));
                this.txtns.setText(rs.getString("BirthDate"));
                
                if (rs.getInt("gioitinh") == 0) {
                    this.radioNu.setSelected(true);
                } else {
                    this.radioNam.setSelected(true);
                }
                this.txtdiemtb.setText(rs.getString("DiemTB"));
                this.txtKhoa.setText(rs.getString("Khoa"));
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_tbsinhvienEmployeesMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed

        try{
            if(txtid.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập id","Thông Báo",JOptionPane.WARNING_MESSAGE);
            }else if(txtname.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập tên","Thông Báo",JOptionPane.WARNING_MESSAGE);
            }else if(txtns.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập ngày sinh","Thông Báo",JOptionPane.WARNING_MESSAGE);
            }else if(txtdiemtb.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập điểm TB","Thông Báo",JOptionPane.WARNING_MESSAGE);
            } else if(txtKhoa.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập khoa","Thông Báo",JOptionPane.WARNING_MESSAGE);
            } else {
                String sql="SELECT * FROM Students WHERE ID=? ";
                PreparedStatement pt=conn.prepareStatement(sql); 
                pt.setString(1,txtid.getText()); 
                ResultSet rs=pt.executeQuery(); 
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "ID đã tồn tại","Thông báo",JOptionPane.ERROR_MESSAGE);
                }else{
                pts=conn.prepareStatement("Insert into Students(ID,Name,BirthDate,gioitinh,DiemTB,Khoa) Values(?,?,?,?,?,?)");
                pts.setString(1,txtid.getText());
                pts.setString(2, txtname.getText());
                pts.setString(3,txtns.getText());
                if (radioNam.isSelected()) {
                    pts.setInt(4, 1);
                } else {
                    pts.setInt(4, 0);
                }
                pts.setString(5,txtdiemtb.getText());
                pts.setString(6, txtKhoa.getText());
                pts.execute();
                    JOptionPane.showMessageDialog(null,"Đã thêm sinh viên thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);
                    Show();
                    txtid.setText("");
                    txtname.setText("");
                    txtns.setText("");
                    txtdiemtb.setText("");
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex,"Thông báo",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        try{
            if(txtid.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập id","Thông Báo",JOptionPane.WARNING_MESSAGE);
            }else if(txtname.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập tên","Thông Báo",JOptionPane.WARNING_MESSAGE);
            }else if(txtns.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập ngày sinh","Thông Báo",JOptionPane.WARNING_MESSAGE);
            }else if(txtdiemtb.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập điểm TB","Thông Báo",JOptionPane.WARNING_MESSAGE);
            } else if(txtKhoa.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Bạn chưa nhập khoa","Thông Báo",JOptionPane.WARNING_MESSAGE);
            } else{
                String sql="SELECT * FROM Students WHERE ID=? ";
                PreparedStatement pt=conn.prepareStatement(sql); 
                pt.setString(1,txtid.getText()); 
                ResultSet rs=pt.executeQuery(); 
                int id = Integer.parseInt(txtid.getText());
                if( rs.next()){
                        pts=conn.prepareStatement("Update Students set Name=?,BirthDate=?, gioitinh=?,DiemTB=?,Khoa=? where ID=?");
                        pts.setString(1,txtname.getText());
                        pts.setString(2, txtns.getText());
                        if (radioNam.isSelected()) {
                            pts.setInt(3, 1);
                        } else {
                            pts.setInt(3, 0);
                        }
                        pts.setString(4,txtdiemtb.getText());
                        pts.setString(5, txtKhoa.getText());
                        pts.setInt(6, id);
                        pts.execute();
                       JOptionPane.showMessageDialog(null,"Sửa sinh viên thành công","Thông báo",JOptionPane.INFORMATION_MESSAGE);                  
                    Show();
                    txtid.setText("");
                    txtname.setText("");
                    txtns.setText("");
                    txtdiemtb.setText("");
                }else{
                    JOptionPane.showMessageDialog(null, "Bạn không được phép sửa id","Thông báo",JOptionPane.ERROR_MESSAGE);
                }

            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Thất bại","Thông báo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        JFileChooser excelFileChooser = new JFileChooser("D:\\");
        excelFileChooser.setDialogTitle("Save As");
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        DefaultTableModel model = new DefaultTableModel();
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showSaveDialog(null);
        if (excelChooser == JFileChooser.APPROVE_OPTION) {
            FileOutputStream excelFOU = null;
            try {
                XSSFWorkbook excelJTableExporter = new XSSFWorkbook();
                XSSFSheet excelSheet = excelJTableExporter.createSheet("JTable Sheet");
                for (int i = 0; i < model.getRowCount() ; i++) {
                    XSSFRow excelRow = excelSheet.createRow(i);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        XSSFCell excelCell = excelRow.createCell(j);
                        excelCell.setCellValue(model.getValueAt(i, j).toString());
                    }
                }   excelFOU = new FileOutputStream(excelFileChooser.getSelectedFile() + ".xlsx");
                BufferedOutputStream excelBOU = new BufferedOutputStream(excelFOU);
                excelJTableExporter.write(excelBOU);
                JOptionPane.showMessageDialog(null, "Xuất dữ liệu dạng Excels thành công!");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Sinhvien.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Sinhvien.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                try {
                    excelFOU.close();
                } catch (IOException ex) {
                    Logger.getLogger(Sinhvien.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_btnExportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sinhvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sinhvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnload;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JTable tbsinhvien;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtdiemtb;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtns;
    private javax.swing.JTextField txttentim;
    private javax.swing.JLabel txttong;
    // End of variables declaration//GEN-END:variables
}
